version: 1.0.{build}
image: Visual Studio 2017
build:
  project: .\VS_NETCORE\VS_NETCORE.sln
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal